# Generated by Django 5.0.6 on 2024-08-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcaster",
            name="lemon_customer_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="broadcaster",
            name="lemon_subscription_item_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
