# Generated by Django 5.0.6 on 2024-08-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_broadcaster_lemon_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcaster",
            name="max_free_runs",
            field=models.IntegerField(default=15),
        ),
    ]
