TWITCH_SUB_EXTERNAL_REFERENCE = "channel.subscription.message"
TWITCH_CHEER_EXTERNAL_REFERENCE = "channel.cheer"

TWITCH_SUB_CONSTANT = "SUB"
TWITCH_CHEER_CONSTANT = "BIT"
TWITCH_EVENT_OPTIONS = [
    [TWITCH_SUB_CONSTANT, TWITCH_SUB_EXTERNAL_REFERENCE],
    [TWITCH_CHEER_CONSTANT, TWITCH_CHEER_EXTERNAL_REFERENCE]
]


NEW_SFX_REQUEST_STATUS = "N"
FAILED_SFX_REQUEST_STATUS = "E"
DONE_SFX_REQUEST_STATUS = "D"
SOUND_EFFECT_REQUEST_STATUS_OPTIONS = [
        [NEW_SFX_REQUEST_STATUS, "New"],
        [FAILED_SFX_REQUEST_STATUS, "Failed"],
        [DONE_SFX_REQUEST_STATUS, "Done"]
    ]


NEW_CHEER_EVENT_LOG_STATUS = "N"
IGNORED_CHEER_EVENT_LOG_STATUS = "I"
FAILED_CHEER_EVENT_LOG_STATUS = "E"
DONE_CHEER_EVENT_LOG_STATUS = "D"

CHEER_EVENT_LOG_STATUS_OPTIONS = [
    [NEW_CHEER_EVENT_LOG_STATUS, "New"],
    [IGNORED_CHEER_EVENT_LOG_STATUS, "Ignored / Didn't match preferences"],
    [FAILED_CHEER_EVENT_LOG_STATUS, "Failed"],
    [DONE_CHEER_EVENT_LOG_STATUS, "Done"],
]