TWITCH_SUB_EXTERNAL_REFERENCE = "channel.subscription.message"
TWITCH_CHEER_EXTERNAL_REFERENCE = "channel.cheer"

TWITCH_SUB_CONSTANT = "SUB"
TWITCH_CHEER_CONSTANT = "BIT"
TWITCH_EVENT_OPTIONS = [
    [TWITCH_SUB_CONSTANT, TWITCH_SUB_EXTERNAL_REFERENCE],
    [TWITCH_CHEER_CONSTANT, TWITCH_CHEER_EXTERNAL_REFERENCE]
]


NEW_STATUS = "N"
FAILED_STATUS = "E"
DONE_STATUS = "D"
IGNORED_STATUS = "I"


SOUND_EFFECT_REQUEST_STATUS_OPTIONS = [
        [NEW_STATUS, "New"],
        [FAILED_STATUS, "Failed"],
        [DONE_STATUS, "Done"]
    ]

CHEER_EVENT_LOG_STATUS_OPTIONS = [
    [NEW_STATUS, "New"],
    [IGNORED_STATUS, "Ignored / Didn't match preferences"],
    [FAILED_STATUS, "Failed"],
    [DONE_STATUS, "Done"],
]