# Generated by Django 5.0.6 on 2024-07-27 14:30

import django.db.models.deletion
import main.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_command", models.BooleanField(default=True)),
                ("command_string", models.CharField(default="$fx", max_length=20)),
                ("cheers_enabled", models.BooleanField(default=False)),
                ("auto_generate", models.BooleanField(default=True)),
                ("auto_play", models.BooleanField(default=True)),
                (
                    "match_bits",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, the match ammount has to be exact to generate a sfx. Otherwise, anything over the set bit ammount will generate a sfx.",
                    ),
                ),
                ("min_bits", models.IntegerField(default=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheerEventLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestmap", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("I", "Ignored / Didn't match preferences"),
                            ("E", "Failed"),
                            ("D", "Done"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("twitch_message_id", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("user_login", models.CharField(blank=True, max_length=150, null=True)),
                ("user_name", models.CharField(blank=True, max_length=150, null=True)),
                ("broadcaster_user_id", models.CharField(max_length=50)),
                ("broadcaster_user_login", models.CharField(max_length=150)),
                ("broadcaster_user_name", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("bits", models.IntegerField(default=0)),
                (
                    "internal_broadcaster_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoundEffectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "elevenlabs_record_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "New"), ("E", "Failed"), ("D", "Done")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=main.models.SoundEffectRequest.upload_sfx_file,
                    ),
                ),
                ("failed_reason", models.TextField()),
                (
                    "cheer_event_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cheereventlogentry",
                    ),
                ),
            ],
        ),
    ]
