# Generated by Django 5.0.6 on 2024-07-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertpreferences",
            name="cheer_eventsub_id",
            field=models.TextField(null=True),
        ),
    ]
