# Generated by Django 5.0.6 on 2024-07-28 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alertpreferences_cheer_eventsub_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertpreferences",
            name="cheers_enabled",
        ),
    ]
