# Generated by Django 5.0.6 on 2024-07-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_alertpreferences_cheers_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertpreferences",
            name="match_command",
            field=models.BooleanField(default=False),
        ),
    ]
