# Generated by Django 5.0.6 on 2024-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_alertpreferences_match_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundeffectrequest",
            name="is_metered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="soundeffectrequest",
            name="usage_record_id",
            field=models.TextField(null=True),
        ),
    ]
