# Generated by Django 5.0.6 on 2024-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_soundeffectrequest_is_metered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertpreferences",
            name="cheer_eventsub_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="soundeffectrequest",
            name="failed_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="soundeffectrequest",
            name="usage_record_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
