# Generated by Django 5.0.6 on 2024-08-04 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_alertpreferences_cheer_eventsub_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soundeffectrequest",
            name="elevenlabs_record_id",
        ),
    ]
