# Generated by Django 5.0.6 on 2024-08-05 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_soundeffectrequest_elevenlabs_record_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cheereventlogentry",
            old_name="timestmap",
            new_name="timestamp",
        ),
    ]
